# =============================================================================
# golangci-lint v2 configuration - Strict settings for production code
# https://golangci-lint.run/usage/configuration/
# =============================================================================

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    # Default linters
    - errcheck          # Check for unchecked errors
    - govet             # Report suspicious constructs
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Static analysis checks (includes gosimple, stylecheck)
    - unused            # Check for unused code
    
    # Additional strict linters
    - bodyclose         # Check HTTP response body is closed
    - dupl              # Code clone detection
    - durationcheck     # Check for two durations multiplied together
    - errname           # Check error naming conventions
    - errorlint         # Find errors not wrapped properly
    - exhaustive        # Check exhaustiveness of enum switch statements
    - copyloopvar       # Detects loop variable copies
    - forcetypeassert   # Finds forced type assertions
    - goconst           # Find repeated strings that could be constants
    - gocritic          # Opinionated linter with many checks
    - gocyclo           # Cyclomatic complexity
    - gosec             # Security checker
    - misspell          # Find commonly misspelled words
    - nakedret          # Find naked returns in long functions
    - nestif            # Reports deeply nested if statements
    - nilerr            # Finds returning nil after checking err != nil
    - noctx             # Find HTTP requests without context
    - nolintlint        # Reports ill-formed nolint directives
    - prealloc          # Find slice declarations that could be preallocated
    - predeclared       # Find code shadowing predeclared identifiers
    - revive            # Fast, configurable linter
    - unconvert         # Remove unnecessary type conversions
    - unparam           # Find unused function parameters
    - wastedassign      # Find wasted assignment statements
    - whitespace        # Find trailing whitespace

formatters:
  enable:
    - gofmt             # Check code is formatted
    - goimports         # Check imports are sorted

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for most projects

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam  # May be too strict for some use cases

  goimports:
    local-prefixes: github.com/cesarempathy/pv-zone-migrator

  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path provided as taint input (false positives)

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - gocyclo
        - errcheck
        - forcetypeassert

    # Exclude cmd files from some checks
    - path: cmd/
      linters:
        - gochecknoinits

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: warning
    - linters:
        - goconst
      severity: warning
